#!/usr/bin/env bash

# Gets the full path to this keymaps repo's directory
REPO_DIR="$(realpath "$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )")"

function symlink_dactyl_custom_keymap() {
  local source_keymap="$REPO_DIR/dactyl_manuform_5x6"
  local symlink_destination="$QMK_HOME/keyboards/handwired/dactyl_manuform/5x6/keymaps/custom"

  if [ ! -d "$symlink_destination" ]; then
    echo "Symlinking keymap"
    ln -sf "$source_keymap" "$symlink_destination"
  else
    echo "Keymap already in place, nothing to do"
  fi
}

function symlink_dactyl_miryoku_keymap() {
  local source_keymap="$REPO_DIR/dactyl_manuform_5x6_miryoku"
  local symlink_destination="$QMK_HOME/keyboards/handwired/dactyl_manuform/5x6/keymaps/manna-harbour_miryoku"

  if [ ! -d "$symlink_destination" ]; then
    echo "Symlinking keymap"
    ln -sf "$source_keymap" "$symlink_destination"
  else
    echo "Keymap already in place, nothing to do"
  fi
}

function symlink_dingo_homerow_keymap() {
  local source_keymap="$REPO_DIR/dingo_homerow"
  local symlink_destination="$QMK_HOME/keyboards/gboards/gergo/keymaps/dingo_homerow"

  if [ ! -d "$symlink_destination" ]; then
    echo "Symlinking keymap"
    ln -sf "$source_keymap" "$symlink_destination"
  else
    echo "Keymap already in place, nothing to do"
  fi
}

function symlink_dingo_keymap() {
  local source_keymap="$REPO_DIR/dingo"
  local symlink_destination="$QMK_HOME/keyboards/gboards/gergo/keymaps/dingo"

  if [ ! -d "$symlink_destination" ]; then
    echo "Symlinking keymap"
    ln -sf "$source_keymap" "$symlink_destination"
  else
    echo "Keymap already in place, nothing to do"
  fi
}

symlink_dactyl_custom_keymap
symlink_dactyl_miryoku_keymap
symlink_dingo_homerow_keymap
symlink_dingo_keymap
